// Loads the imported curriculum (content/curriculum/*.json) into memory at boot.
// Generated by scripts/import-curriculum.mjs — see that file to re-import.
// Source freshness: the current chapter JSON was ingested from the Jul 15, 2026
// HAB Sales OS Master Curriculum .htm (index.json generatedAt 2026-07-17T01:14Z,
// v1.1 verification 2026-07-16: all 16 chapters present and non-empty).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(__dirname, '..', 'content', 'curriculum');

let chaptersList = [];
const chaptersBySlug = new Map();
const modulesByKey = new Map();

if (fs.existsSync(path.join(DIR, 'index.json'))) {
  const idx = JSON.parse(fs.readFileSync(path.join(DIR, 'index.json'), 'utf8'));
  for (const meta of idx.chapters) {
    const full = JSON.parse(fs.readFileSync(path.join(DIR, `${meta.slug}.json`), 'utf8'));
    chaptersBySlug.set(meta.slug, full);
    if (full.moduleKey) modulesByKey.set(full.moduleKey, full);
    chaptersList.push(meta);
  }
  console.log(`[curriculum] loaded ${chaptersList.length} chapters (${modulesByKey.size} trackable modules)`);
} else {
  console.warn('[curriculum] content/curriculum/index.json missing — run scripts/import-curriculum.mjs');
}

export const Curriculum = {
  loaded: chaptersList.length > 0,
  chapters: () => chaptersList,                                  // index metadata, in book order
  modules:  () => chaptersList.filter(c => c.kind === 'module'), // M1–M9 metadata
  refs:     () => chaptersList.filter(c => c.kind === 'ref'),
  bySlug:   (slug) => chaptersBySlug.get(slug) || null,          // full chapter (intro + sections html)
  byModuleKey: (key) => modulesByKey.get(key) || null,
  sectionCount: (moduleKey) => modulesByKey.get(moduleKey)?.sections.length || 0,
  totalSections: () => [...modulesByKey.values()].reduce((n, c) => n + c.sections.length, 0),
};
